apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apicharts.fullname" . }}
type: Opaque
data:
  # APIKEYをこのまま載せるのはセキュリティ的にアウト。これはあくまでサンプル
  APIKEY: {{ "8oZ73ujfLImshH6xaf8wypGd8o6kp1U0NPSjsnQ6wvUt4FaLLO" | b64enc }}
