apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.deployment.mongodb.name }}
 namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.deployment.mongodb.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.deployment.mongodb.name }}
    spec:
      containers:
        - name:  {{ .Values.deployment.mongodb.name }}
          image:  "{{ .Values.image.mongodb.repository }}:{{ .Values.image.mongodb.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.deployment.mongodb.port }}
          volumeMounts:
            - name:  {{ .Values.volumes.claim.mongodb.name }}
              mountPath:  {{ .Values.volumes.claim.mongodb.mountPath }}
      volumes:
        - name:  {{ .Values.volumes.claim.mongodb.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.claim.mongodb.name }}

