# POD
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
    env: study
spec:
  containers:
    - name: nginx
      image: nginx:1.17.2-alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    app: web # podのlabelを指定する
    env: study
  ports:
    - port: 80 # サービス受付Port
      targetPort: 80 # コンテナ転送先Port
      nodePort: 30000 # ノード受付Port(http://localhost:30000/でアクセスできるようになる)
