apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.claim.mongodb.name }}
  namespace: {{ .Release.Name }}
spec:
  accessModes:
    -  {{ .Values.volumes.claim.mongodb.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.claim.mongodb.storage }}
