replicaCount: 2

image:
  pullPolicy: IfNotPresent
  store:
    repository: laithharb/store-app
    tag: "latest"
  products:
    repository: laithharb/products-api
    tag: "latest"
  mongodb:
    repository: mongo
    tag: "latest"

# serviceAccount:
#   create: true
#   annotations: {}
#   name: ""

# podAnnotations: {}

service:
  store:
    name: store-cluster-ip-service
    type: ClusterIP
    port: 80
  products:
    name: products-cluster-ip-service
    type: ClusterIP
    port: 5002
  mongodb:
    name: mongodb-cluster-ip-service
    type: ClusterIP
    port: 27017

deployment:
  store:
    name: store
    port: 80
  products:
    name: product-api
    port: 5002
  mongodb:
    name: mongodb
    port: 27017

# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
