apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
data:
  # Base64で指定する
  # echo -n 'Hello World!' | base64
  message: SGVsbG8gV29ybGQh
  # ファイルをbase64化(catコマンドでも良い)
  # echo -n 'YOUR-SECRET-KEY' | base64
  keyfile: WU9VUi1TRUNSRVQtS0VZ

---
apiVersion: v1
kind: Pod
metadata:
  name: sample
  labels:
    name: sample
  namespace: default
spec:
  containers:
    - name: sample
      image: nginx:1.17.2-alpine
      # Secretを環境変数にMountする
      env:
        - name: MESSAGE
          valueFrom:
            secretKeyRef:
              name: sample-secret # Secret名
              key: message # Secretに設定したKey名
      # SecretをVolumesにMountする
      volumeMounts:
        - name: secret-storage # Volumeの名前
          mountPath: /home/nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: secret-storage # Volumeの名前
      secret:
        secretName: sample-secret
        items:
          - key: keyfile # Secretに設定した値
            path: keyfile # Secretに設定した値
