apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.store.name }}
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.service.store.type }}
  selector:
    component: {{ .Values.deployment.store.name }}
  ports:
    - port: {{ .Values.service.store.port }}
      targetPort: {{ .Values.service.store.port }}
