apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.store.name }}
spec:
  type: {{ .Values.service.store.type }}
  selector:
    component: {{ .Values.deployment.store.name }}
  ports:
    - nodePort: {{ .Values.service.store.nodePort }}
      port: {{ .Values.service.store.port }}
      targetPort: {{ .Values.service.store.port }}
