apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.mongodb.name }}
spec:
  type: {{ .Values.service.mongodb.type }}
  selector:
    component: {{ .Values.pod.mongodb.name }}
  ports:
    - name: db
      protocol: TCP
      port: {{ .Values.service.mongodb.port }}
      targetPort: {{ .Values.service.mongodb.port }}
