apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.products.name }}
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.service.products.type }}
  selector:
    component: {{ .Values.deployment.products.name }}
  ports:
    - port: {{ .Values.service.products.port }}
      targetPort: {{ .Values.service.products.port }}
