apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.rabbitmq.name }}
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.service.rabbitmq.type }}
  selector:
    component: {{ .Values.deployment.rabbitmq.name }}
  ports:
    - name: {{ .Values.deployment.rabbitmq.name }}
      protocol: TCP
      port: {{ .Values.service.rabbitmq.port }}
      targetPort: {{ .Values.service.rabbitmq.port }}
