apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.store.name }}
                port:
                  number: {{ .Values.service.store.port }}
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.products.name }}
                port:
                  number: {{ .Values.service.products.port }}
