apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
  sample.cfg: | # Mount先にファイルが作られる
    user: tanaka.taro
  type: "application" # 環境変数設定用(envコマンドで確認できる)

---
apiVersion: v1
kind: Pod
metadata:
  name: sample
  labels:
    name: sample
spec:
  containers:
    - name: sample
      image: nginx:1.17.2-alpine
      # ConfigMapを環境変数にMountする
      env:
        - name: TYPE
          valueFrom:
            configMapKeyRef:
              name: sample-config # ConfigMap名
              key: type # configMapに設定したKey名
      # ConfigMapをVolumesにMountする
      volumeMounts:
        - name: config-storage # Volumeの名前
          mountPath: /home/nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: config-storage # Volumeの名前
      configMap:
        name: sample-config
        items:
          - key: sample.cfg # ConfigMapに設定した値
            path: sample.cfg # ConfigMapに設定した値
